### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible-network/ansible_collections.junipernetworks.junos/pull/3
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/320
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 43d7811a53aeaf3b0ce0762115eacbc1e58cadf5

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 991c62a7cf3b806180ba02b5bfb2305c9fe710d6

**Pull request merged**
